name: Bug Report
description: Report a bug or issue with MCPing
title: "[Bug] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure MCPing with '...'
        2. Send notification with parameters '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      placeholder: Paste error logs here...
      render: shell

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of MCPing are you using?
      placeholder: 0.0.3
    validations:
      required: true

  - type: dropdown
    id: transport
    attributes:
      label: Transport Mode
      description: Which transport mode were you using?
      options:
        - STDIO
        - HTTP
        - Both
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js Version
      description: What version of Node.js are you using?
      placeholder: v18.0.0
    validations:
      required: true

  - type: input
    id: macos
    attributes:
      label: macOS Version
      description: What version of macOS are you using?
      placeholder: 14.0 Sonoma
    validations:
      required: true

  - type: dropdown
    id: client
    attributes:
      label: MCP Client
      description: Which MCP client are you using?
      options:
        - Claude Desktop
        - Zed
        - Windsurf
        - Cursor
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...