name: Documentation
description: Report issues or suggest improvements for documentation
title: "[Docs] "
labels: ["documentation", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please fill out the form below.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect documentation
        - Unclear documentation
        - Documentation enhancement
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Documentation Location
      description: Where in the documentation did you find this issue?
      placeholder: e.g., README.md, API section, Installation guide

  - type: textarea
    id: issue
    attributes:
      label: Issue Description
      description: Describe the documentation issue
      placeholder: What's wrong or missing in the documentation?
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Improvement
      description: How would you improve this documentation?
      placeholder: Describe your suggested changes...
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: If applicable, provide code examples that should be included
      placeholder: |
        ```typescript
        // Example code here
        ```
      render: markdown

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help improve the documentation?
      options:
        - label: I would be willing to submit a PR for this documentation
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the documentation issue
      placeholder: Any additional information...